import os
import uuid
from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.responses import FileResponse
from rq.job import Job
from rq.exceptions import NoSuchJobError
import logging
from pydantic import BaseModel

from Core.auth import get_current_active_user
from BD.models import User
# Shared redis queue object (we could import the existing one from analysis_router if we refactor, but for DB1 we need to instantiate it)
from redis import Redis
from rq import Queue
from Core.config import get_settings

settings = get_settings()
logger = logging.getLogger("export_router")

# Use RQ_REDIS_URL to avoid conflict with pub/sub
redis_url = getattr(settings, "RQ_REDIS_URL", "redis://redis:6379/1")
redis_conn = Redis.from_url(redis_url)
task_queue = Queue("demeter_tasks", connection=redis_conn)

router = APIRouter(prefix="/export", tags=["Exports"])

class ExportRequest(BaseModel):
    experimento_id: int
    fecha_referencia: str
    rango_dias: int

@router.post("/plants", summary="Start Async Export Job")
async def start_export(req: ExportRequest, current_user: User = Depends(get_current_active_user)):
    """
    Enqueues an RQ job to extract and process plant telemetry data asynchronously.
    Returns a Job ID immediately to avoid blocking the API.
    """
    job_id = str(uuid.uuid4())
    logger.info(f"User {current_user.username} requested data export. Enqueuing Job {job_id}")
    
    try:
        # Import task function as string path to avoid circular imports or loading heavy libraries in API memory
        job = task_queue.enqueue(
            "Worker.tasks.export_experiment_data", 
            req.experimento_id,
            req.fecha_referencia,
            req.rango_dias,
            job_id=job_id,
            job_timeout='10m'
        )
        return {"status": "enqueued", "job_id": job.get_id()}
    except Exception as e:
        logger.error(f"Failed to enqueue export job: {e}")
        raise HTTPException(status_code=500, detail="Failed to enqueue background job.")

@router.get("/status/{job_id}", summary="Check Export Job Status")
async def check_export_status(job_id: str, current_user: User = Depends(get_current_active_user)):
    """
    Check the current status of the requested job in the Redis Queue.
    """
    try:
        job = Job.fetch(job_id, connection=redis_conn)
        status = job.get_status() # 'queued', 'started', 'finished', 'failed', 'deferred', 'scheduled'
        
        response = {"job_id": job_id, "status": status}
        
        if status == "finished":
            response["result"] = job.result
            response["download_url"] = f"{settings.API_PREFIX}/export/download/{job_id}"
        elif status == "failed":
            response["error"] = str(job.exc_info)
            
        return response
    except NoSuchJobError:
        raise HTTPException(status_code=404, detail="Job not found")

@router.get("/download/{job_id}", summary="Download Completed Export File")
async def download_export(job_id: str):
    """
    Downloads the resulting zip file generated by the RQ worker.
    """
    # Fetch job to get the correct return value path
    try:
        job = Job.fetch(job_id, connection=redis_conn)
        if job.get_status() != "finished":
            raise HTTPException(status_code=400, detail="Job is not finished yet.")
            
        file_path = job.result
        
        if not file_path or not os.path.exists(file_path):
            raise HTTPException(status_code=404, detail="File could not be found.")
            
        return FileResponse(
            path=file_path, 
            media_type='application/zip', 
            filename=f"Exportacion_Demeter_{job_id}.zip"
        )
    except NoSuchJobError:
        raise HTTPException(status_code=404, detail="Job not found")
