"""Initial LIMS Architecture

Revision ID: eb2b85ec72b6
Revises: 
Create Date: 2026-02-22 16:48:16.374923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb2b85ec72b6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('device_type', sa.String(), nullable=False),
    sa.Column('gpio_pin', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_id'), 'devices', ['id'], unique=False)
    op.create_table('pin_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('pin', sa.Integer(), nullable=False),
    sa.Column('state', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pin_history_id'), 'pin_history', ['id'], unique=False)
    op.create_index(op.f('ix_pin_history_node_id'), 'pin_history', ['node_id'], unique=False)
    op.create_index(op.f('ix_pin_history_timestamp'), 'pin_history', ['timestamp'], unique=False)
    op.create_table('plants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('identificador_fisico', sa.String(), nullable=False),
    sa.Column('especie_variedad', sa.String(), nullable=False),
    sa.Column('fecha_siembra', sa.Date(), nullable=False),
    sa.Column('estado_vital', sa.String(), nullable=False),
    sa.Column('metadata_cientifica', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_id')
    )
    op.create_index(op.f('ix_plants_id'), 'plants', ['id'], unique=False)
    op.create_index(op.f('ix_plants_identificador_fisico'), 'plants', ['identificador_fisico'], unique=True)
    op.create_table('system_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.Integer(), nullable=False),
    sa.Column('battery_mv', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_history_id'), 'system_history', ['id'], unique=False)
    op.create_index(op.f('ix_system_history_node_id'), 'system_history', ['node_id'], unique=False)
    op.create_index(op.f('ix_system_history_timestamp'), 'system_history', ['timestamp'], unique=False)
    op.create_table('telemetry_th',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetry_th_id'), 'telemetry_th', ['id'], unique=False)
    op.create_index(op.f('ix_telemetry_th_node_id'), 'telemetry_th', ['node_id'], unique=False)
    op.create_index(op.f('ix_telemetry_th_timestamp'), 'telemetry_th', ['timestamp'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_activity_log_timestamp', 'activity_log', ['timestamp'], unique=False)
    op.create_index(op.f('ix_activity_log_id'), 'activity_log', ['id'], unique=False)
    op.create_table('experiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('api_key', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiments_api_key'), 'experiments', ['api_key'], unique=True)
    op.create_index(op.f('ix_experiments_id'), 'experiments', ['id'], unique=False)
    op.create_table('sequences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sequences_id'), 'sequences', ['id'], unique=False)
    op.create_table('experimento_planta_link',
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('linked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('experiment_id', 'plant_id')
    )
    op.create_table('sequence_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sequence_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('target_state', sa.Boolean(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['sequence_id'], ['sequences.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sequence_steps_id'), 'sequence_steps', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sequence_steps_id'), table_name='sequence_steps')
    op.drop_table('sequence_steps')
    op.drop_table('experimento_planta_link')
    op.drop_index(op.f('ix_sequences_id'), table_name='sequences')
    op.drop_table('sequences')
    op.drop_index(op.f('ix_experiments_id'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_api_key'), table_name='experiments')
    op.drop_table('experiments')
    op.drop_index(op.f('ix_activity_log_id'), table_name='activity_log')
    op.drop_index('idx_activity_log_timestamp', table_name='activity_log')
    op.drop_table('activity_log')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_telemetry_th_timestamp'), table_name='telemetry_th')
    op.drop_index(op.f('ix_telemetry_th_node_id'), table_name='telemetry_th')
    op.drop_index(op.f('ix_telemetry_th_id'), table_name='telemetry_th')
    op.drop_table('telemetry_th')
    op.drop_index(op.f('ix_system_history_timestamp'), table_name='system_history')
    op.drop_index(op.f('ix_system_history_node_id'), table_name='system_history')
    op.drop_index(op.f('ix_system_history_id'), table_name='system_history')
    op.drop_table('system_history')
    op.drop_index(op.f('ix_plants_identificador_fisico'), table_name='plants')
    op.drop_index(op.f('ix_plants_id'), table_name='plants')
    op.drop_table('plants')
    op.drop_index(op.f('ix_pin_history_timestamp'), table_name='pin_history')
    op.drop_index(op.f('ix_pin_history_node_id'), table_name='pin_history')
    op.drop_index(op.f('ix_pin_history_id'), table_name='pin_history')
    op.drop_table('pin_history')
    op.drop_index(op.f('ix_devices_id'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
