services:
  demeter-core:
    build:
      context: .
      dockerfile: Software/Raspberry/Dockerfile
    container_name: demeter-core
    privileged: true
    volumes:
      - ./Software/Raspberry/data:/app/Software/Raspberry/data
      - ./Software/Raspberry/logs:/app/Software/Raspberry/logs
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    environment:
      - DEMETER_PORT=/dev/ttyUSB0
      # Point to specific internal paths
      - DEMETER_LOG_FILE=/app/Software/Raspberry/logs/demeter.log
      - DEMETER_DB_NAME=demeter.db
      - PYTHONUNBUFFERED=1
      # Connect to Backend on Host or specific IP
      - DEMETER_HOST=patata.monters.org
      - DEMETER_SOCKET_PORT=443
    restart: always
    network_mode: "host"
