services:
  backend:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER:-danielmf31}/proyecto_demeter/backend:latest
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    container_name: demeter-server-backend
    restart: always
    ports:
      - "8000:8000"

  frontend:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER:-danielmf31}/proyecto_demeter/frontend:latest
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    container_name: demeter-server-frontend
    depends_on:
      - backend
    restart: always
    ports:
      - "80:80"

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: demeter-cloudflared
    command: tunnel --no-autoupdate run --protocol http2 --token eyJhIjoiOGUzMDU1NDM1MjEyNjdhNzEzY2I2NGQ2MGJmZjQwZTMiLCJ0IjoiMTNiNjBjNmUtZjllNS00OTQ0LTg4YTktODAxY2EyMzBlYzg0IiwicyI6Ik9ESXdOelZoWXprdE1tSXlPUzAwT0RRNExXSXpaV0l0TWpjNU56ZGxPVEZpT0dWaSJ9
    restart: always
