stateDiagram-v2
    direction LR

    %% --- 1. Generación y Envío (TX) ---
    state "Fase de Creación (TX)" as TX {
        [*] --> ObjetoComando : GUI/Código crea `SetGpio(pin=2, val=1)`
        ObjetoComando --> Serializando : `protocol.serialize(cmd)`
        Serializando --> Empaquetando : Agrega Header (SYNC, LEN, IDs)
        Empaquetando --> CalculandoCRC : Suma Payload + Header
        CalculandoCRC --> BytesListos : Append CRC Byte
        BytesListos --> Enviando : `transport.send(bytes)`
    }

    %% --- Medio físico ---
    BytesListos --> BufferRX : Cable UART / Aire
    

    %% --- 2. Recepción y Parseo (RX) ---
    state "Fase de Parseo (RX)" as RX {
        state "Buffer Stream" as Stream
        
        [*] --> WaitSync : Inicio
        WaitSync --> ReadHeader : Recibe `0xFE`
        WaitSync --> WaitSync : Basura (Ignorar)
        
        ReadHeader --> ReadPayload : Lee LEN, Flags, CMD_ID
        ReadPayload --> CheckCRC : Lee N bytes de Payload
        
        CheckCRC --> Dispatch : CRC Coincide
        CheckCRC --> WaitSync : CRC Error (Drop)
    }

    %% --- 3. Ejecución ---
    state "Fase de Ejecución" as Exec {
        Dispatch --> Lookup : `registry.get(CMD_ID)`
        Lookup --> Ejecutando : Invoca `_parse_set_gpio`
        Ejecutando --> SistemaDestino : Llama a `GPIO.setPin(2, 1)`
        SistemaDestino --> [*] : Fin
    }

    TX --> RX
    RX --> Exec
