direction: right
vars: {
  d2-config: {
    layout-engine: dagre
  }
}
style: {
  stroke: "#2b6cb0"
  fill: "white"
}

title: Diagrama C4 Nivel 3 - Componentes (Nodo Sensor ESP32)

"Nodo Gateway (RF)": {
  shape: rectangle
  style: { fill: "#e9c46a" }
}

"Nodo Sensor (ESP32)": {
  style: {
    fill: "#ebf8ff"
    stroke: "#2b6cb0"
    stroke-dash: 5
    stroke-width: 2
  }

  "Despachador Inalámbrico": {
    shape: rectangle
    description: "A la espera de comandos GetSensor"
  }

  "Lector de Periféricos": {
    shape: rectangle
    description: "Polling activo bajo demanda desde DHT22 o Buses I2C"
  }

  "Empaquetador de Datos": {
    shape: rectangle
    description: "Devuelve telemetría estructurada"
  }
}

"Sistema de Sensores": {
  shape: cylinder
  style: { fill: "#f4a261" }
}

"Nodo Gateway (RF)" -> "Despachador Inalámbrico": "Comando: GetSensor"
"Despachador Inalámbrico" -> "Lector de Periféricos": "Manda medir"
"Lector de Periféricos" -> "Sistema de Sensores": "Lectura Eléctrica"

"Sistema de Sensores" -> "Lector de Periféricos": "Dato devuelto (Temperatura, etc)"
"Lector de Periféricos" -> "Empaquetador de Datos": "Pasa payload"
"Empaquetador de Datos" -> "Nodo Gateway (RF)": "Transmite Datos de Sensor por Radio"
