[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "proyecto_demeter"
version = "0.1.0"
description = "Plantilla estandarizada para proyectos de cualquier tipo, soporte para Python y Cpp"
authors = [
    { name = "Daniel" }
]
requires-python = ">=3.11"
dependencies = [
    "pydantic>=2.0",
    "pydantic-settings",
    "python-dotenv",
    "pyserial",
    "RPi.GPIO"
]

[tool.hatch.build.targets.wheel]
packages = ["src/proyecto_demeter"]
