site_name: "Proyecto_Demeter"
site_description: "Plantilla estandarizada para proyectos de cualquier tipo, soporte para Python y Cpp"
site_author: "Daniel"

theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - content.code.copy

plugins:
  - search

nav:
  - Inicio: index.md
  - Referencia API:
      - Core: reference/core.md
      - Utils: reference/utils.md
